#!/usr/bin/env bash
#
# Simple script to check the current status of OneDrive
# OneDrive solution tested on: https://github.com/abraunegg/onedrive
#
LAST_LOG=$(journalctl -b --user-unit onedrive.service -r -n 1 | sed -e 's/.*: //g')
COLOR='#FFFFFF'         # White

case $LAST_LOG in
    *complete)
        TEXT='synced'
        COLOR='#7DF9FF'         # Electric Blue
    ;;
    Starting*|Synching*|Moving*|Uploading*|Downloading*|Creating*)
        TEXT='syncing'
        COLOR='#7DF9FF'         # Electric Blue
    ;;
    *check*)
        TEXT='checking'
    ;;
    Initializing*|Started*|Notification*|Config*|OneDrive*)
        TEXT='init.'
    ;;
    *)
        echo ""
    ;;
esac

echo "OneDrive: $TEXT  : :"  # long text
echo                    # short text
echo "$COLOR"           # color
