#!/usr/bin/env bash
#
# Simple script to check the current status of OneDrive
# OneDrive solution tested on: https://github.com/abraunegg/onedrive
#
LAST_LOG=$(journalctl -b --user-unit onedrive.service -r -n 1 | sed -e 's/.*: //g')

case $LAST_LOG in
    *complete)
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss synced weather_clouds Good
    ;;
    Starting*|Synching*|Moving*|Uploading*|Downloading*|Creating*|Uploading*|Deleting*|Received*|done*|*check*)
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss syncing weather_default Info
    ;;
    Initializing*|Started*|Notification*|Config*|OneDrive*)
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss init. weather_clouds Idle
    ;;
    Stopped*)
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss inactive weather_rain Idle
    ;;
    *'resolve host name'*)
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss 'inet' weather_thunder Critical
    ;;
    *)
        TEXT="$(echo $LAST_LOG | cut -d ' ' -f1).."
        busctl --user call i3.status.rs /OnedriveStatus i3.status.rs SetStatus sss "$TEXT" weather_thunder Warning
    ;;
esac
